
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NoExisteTipoPublicacion", targetNamespace = "http://servidor/")
public class NoExisteTipoPublicacion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoExisteTipoPublicacion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoExisteTipoPublicacion_Exception(String message, NoExisteTipoPublicacion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NoExisteTipoPublicacion_Exception(String message, NoExisteTipoPublicacion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.NoExisteTipoPublicacion
     */
    public NoExisteTipoPublicacion getFaultInfo() {
        return faultInfo;
    }

}
