
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NoExisteEmpresa", targetNamespace = "http://servidor/")
public class NoExisteEmpresa_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoExisteEmpresa faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoExisteEmpresa_Exception(String message, NoExisteEmpresa faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NoExisteEmpresa_Exception(String message, NoExisteEmpresa faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.NoExisteEmpresa
     */
    public NoExisteEmpresa getFaultInfo() {
        return faultInfo;
    }

}
