
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NoExisteOfertaEmpresa", targetNamespace = "http://servidor/")
public class NoExisteOfertaEmpresa_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoExisteOfertaEmpresa faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoExisteOfertaEmpresa_Exception(String message, NoExisteOfertaEmpresa faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NoExisteOfertaEmpresa_Exception(String message, NoExisteOfertaEmpresa faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.NoExisteOfertaEmpresa
     */
    public NoExisteOfertaEmpresa getFaultInfo() {
        return faultInfo;
    }

}
